# Params default config with custom Theme-related and CMS specifics.

site_keywords: [free, open-source, CAD, software, tool, parametric, modeling, model, design, product, engineering, manufacturing, community, workbench, FOSS, 3D, BIM, CAM, FEM, FEA]
site_authors: FreeCAD
site_logo: FreeCAD-wordmark.svg

default_icon: FreeCAD-symbol-mono.svg
default_chroma: auto # dark or light

style:
  accent-color: hsl(210, 75%, 55%)
  radius: 0.5rem
  font-sans: '-apple-system, Arial, Helvetica, "Helvetica Neue", Verdana, BlinkMacSystemFont, "Avenir Next", Avenir, "Nimbus Sans L", "Noto Sans", "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", sans-serif'
  font-mono: '"Ubuntu Mono", monospace, "Lucida Console", Monaco, Menlo, Consolas, "Andale Mono"'

show_date: true
show_taxonomy: true
show_word_count: true
show_reading_time: true
show_translations: false
show_pagination: true
show_popover: true

# JS scripts
enable_js_copy: true
enable_js_details: true
enable_js_toc: true
enable_js_carousel: true
enable_js_compare: true
enable_js_canvas: true

enable_fediverse: true

git_repository: https://github.com/freecad/website

socials:
  - forum: https://forum.freecad.org
  - github: https://github.com/freecad
  - codeberg: https://codeberg.org/freecad
  - mastodon: https://social.freecad.org/@freecad
  - reddit: https://www.reddit.com/r/freecad
  - matrix: https://matrix.to/#/#FreeCAD_FreeCAD:gitter.im
  - discord: https://discord.gg/w2cTKGzccC
  - facebook: https://www.facebook.com/freecad
  - linkedin: https://www.linkedin.com/groups/4295230

# Image processing
resize_format: webp
resize_dimensions:
  cover: [500x250, 1000x500]
  card: [500x250]

# Remote resources fetching
timeout: 5s


# Custom partials parameters. For localized strings, see relevant content files.

# Download Section
download:
  - os: windows
    label: Windows
    order: 1
    packages:
      - key: msi
        label: x86_64 Installer
        alt: WINDOWS-MSI
      - key: zip
        label: x86_64 Portable
        alt: WINDOWS-ZIP
  - os: mac
    label: macOS
    order: 2
    packages:
      - key: x86
        label: Intel x86
        alt: MACOS-X86
      - key: arm
        label: Apple Silicon
        alt: MACOS-ARM
  - os: linux
    label: GNU/Linux
    order: 3
    packages:
      - key: x86
        label: x86_64 AppImage
        alt: LINUX-X86
      - key: arm
        label: AArch64 AppImage
        alt: LINUX-AARCH64