# Params default config with custom Theme-related and CMS specifics.

site_authors: FreeCAD
site_logo: FreeCAD-wordmark.svg
site_keywords:
  - free
  - open-source
  - CAD
  - software
  - tool
  - parametric
  - modeling
  - model
  - design
  - product
  - engineering
  - manufacturing
  - community
  - workbench
  - FOSS
  - 3D
  - BIM
  - CAM
  - FEM
  - FEA

default_icon: FreeCAD-symbol-mono.svg
default_chroma: auto # dark or light

style:
  accent-color: hsl(210, 75%, 55%)
  radius: 0.5rem
  font-sans: '-apple-system, Arial, Helvetica, "Helvetica Neue", Verdana, BlinkMacSystemFont, "Avenir Next", Avenir, "Nimbus Sans L", "Noto Sans", "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", sans-serif'
  font-mono: '"Ubuntu Mono", monospace, "Lucida Console", Monaco, Menlo, Consolas, "Andale Mono"'

# Theme features
show_date: true
show_taxonomy: true
show_word_count: true
show_reading_time: true
show_translations: false
show_pagination: true
show_popover: true
enable_hue: true

# JS scripts
enable_js_copy: true
enable_js_details: true
enable_js_toc: true
enable_js_carousel: true
enable_js_compare: true
enable_js_canvas: true
enable_js_calendar: true
enable_js_addons: true

# External and remote interaction
allow_remote: true
enable_fediverse: true

# Theme and pages debug info
enable_debug: false

# Remote resources fetching
timeout: 5s

git_repository: https://github.com/freecad/website

socials:
  - forum: https://forum.freecad.org
  - github: https://github.com/freecad
  - codeberg: https://codeberg.org/freecad
  - mastodon: https://social.freecad.org/@freecad
  - reddit: https://www.reddit.com/r/freecad
  - matrix: https://matrix.to/#/#FreeCAD_FreeCAD:gitter.im
  - discord: https://discord.gg/w2cTKGzccC
  - facebook: https://www.facebook.com/freecad
  - linkedin: https://www.linkedin.com/groups/4295230

# Image processing
resize_format: webp
resize_dimensions:
  - 400
  - 800
  - 1600

# Image default attributes
image_loading: lazy
image_priority: low
image_decoding: async

# Custom partials parameters. For localized strings, see relevant content files.

# Download Section
download:
  - os: windows
    label: Windows
    subtitle: Windows 10+
    order: 1
    packages:
      - key: msi
        label: Installer
        meta: x86-64
      - key: zip
        label: Portable
        meta: x86-64
  - os: mac
    label: macOS
    subtitle: macOS 12+ Monterey
    order: 2
    packages:
      - key: x86
        label: Intel
        meta: x86-64
      - key: arm
        label: Apple Silicon
        meta: arm64
  - os: linux
    label: GNU/Linux
    subtitle: Multiple Distributions
    order: 3
    packages:
      - key: x86
        label: x86-64 AppImage
        meta: amd64
      - key: arm
        label: AArch64 AppImage
        meta: arm64

# Calendar in Community
calendar:
  host: https://open-web-calendar.hosted.quelltext.eu/calendar.html
  url: https://cloud.freecad.org/remote.php/dav/public-calendars/ZtJiizXtSqBaacwo
  title: FreeCAD Calendar
  tabs:
    - month
    - week
    - agenda
  skin: terrace
  menu: false
  target: _blank

# Telemetry in Community
telemetry:
  entries_max: 12
  order:
    - freecad_version
    - language
    - system
    - machine
    - mods
    - workbench_default
    - theme
    - screen_resolution
    - navigation_style
    - navigation_orbit_style
    - ui_toolbar_icon_size
    - python_version